DEFINES = -DMODEL=System_Recv_io -DNUMST=2 -DNCSTATES=38 -DHAVESTDIO -DMODEL_HAS_DYNAMICALLY_LOADED_SFCNS=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DTID01EQ=1 -DTERMFCN=1 -DONESTEPFCN=1 -DMAT_FILE=0 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0
EXEC = recv
EXEC_DBG = $(EXEC)_dbg

$(EXEC): *.cpp
	g++ -pthread $(DEFINES) $^ -o $@

$(EXEC_DBG): *.cpp
	g++ -ggdb3 -pthread $(DEFINES) $^ -o $@

clean:
	rm -f $(EXEC) $(EXEC_DBG)